# Hemadri Pali -PLM Developer @ ZF Group
title: Hemadri
twitter_username: hemadri-lab
name: Hemadri Pali
 GitHub
   url: https://github.com/hemadri-lab
 

skills:
 - Groovy
 - Spring MVC
 - Spring Boot


blogfeed: http://automateddeveloper.blogspot.com/feeds/posts/default


Roles:
 - title: Senior Engineer
   start: 2014
   end: Ongoing
   employer: ZF Group
   description: PLM Developer for an automotive domain with 8 years exp.


education:
 - level: BTECH 
   date: 2014
   subject: Elect And Comm.
   school: University of BNagpur

github:
 - robhinds/twitter-sentiment-analysis
 - robhinds/spring-reactor-twitter
 - robhinds/microservices


apps:
 - name: Chuck the Quiz
   platform: Android
   url: https://play.google.com/store/apps/details?id=com.tmm.android.chuck&feature=search_result#?t=W251bGwsMSwxLDEsImNvbS50bW0uYW5kcm9pZC5jaHVjayJd
   description: A basic early Android app (open sourced)


additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others.  In my current role Groovy is the primary language used - and I am familiar with many of the languages features and quirks (including writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>).
